version: 2
jobs:
  build:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run:
          command: |
            go mod download
            go build ./...
            go test ./...
